version: '3.8'

services:
  freshtrack-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freshtrack-app
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshtrack.rule=Host(`freshtrack.local`)"
      - "traefik.http.services.freshtrack.loadbalancer.server.port=80"

  # Optional: Reverse Proxy (Traefik)
  traefik:
    image: traefik:v2.10
    container_name: freshtrack-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    profiles:
      - proxy

networks:
  default:
    name: freshtrack-network